version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "yarn install && yarn dev"
    ports:
      - "4000:4000"
    volumes:
      - .:/web
      - ./data/history:/history
